### ISSUE TITLE
`storage-metadata` service panics on gRPC calls from `accounts` service

### ISSUE THREAD

**Issue by NexZhu** [owncloud/ocis-charts#42]
`storage-metadata` service panics on gRPC calls from `accounts` service:

I'm using the latest commit of the chart, persistent volumes are mounted successfully.

Error log from `storage-metadata` pod:
```
goroutine 516 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/cs3org/reva/v2/internal/grpc/interceptors/recovery.recoveryFunc({0x40b3cc0, 0xc0013d4660}, {0x3b67c40, 0x5a13ee0})
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/interceptors/recovery/recovery.go:48 +0x31
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x40b3cc0, 0xc0013d4660}, {0x3b67c40, 0x5a13ee0}, 0xc000d10940)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:61 +0x36
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:29 +0x7b
panic({0x3b67c40, 0x5a13ee0})
	runtime/panic.go:1038 +0x215
github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs/node.(*Node).InternalPath(...)
	github.com/cs3org/reva/v2@v2.1.0/pkg/storage/utils/decomposedfs/node/node.go:457
github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs.(*Decomposedfs).CreateStorageSpace(0xc0001d22d0, {0x40b3cc0, 0xc0013d4960}, 0xc0000c2a80)
	github.com/cs3org/reva/v2@v2.1.0/pkg/storage/utils/decomposedfs/spaces.go:94 +0x4a0
github.com/cs3org/reva/v2/internal/grpc/services/storageprovider.(*service).CreateStorageSpace(0xc0001d2320, {0x40b3cc0, 0xc0013d4960}, 0xc0000c2a80)
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/services/storageprovider/storageprovider.go:435 +0x46
github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1._ProviderAPI_CreateStorageSpace_Handler.func1({0x40b3cc0, 0xc0013d4960}, {0x3ed6920, 0xc0000c2a80})
	github.com/cs3org/go-cs3apis@v0.0.0-20220126114148-64c025ccdd19/cs3/storage/provider/v1beta1/provider_api.pb.go:5948 +0x78
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x40b3cc0, 0xc0013d4870}, {0x3ed6920, 0xc0000c2a80}, 0xc0008fc040, 0xc0001b2c30)
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.31.0/interceptor.go:325 +0x61c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d4870}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/cs3org/reva/v2/internal/grpc/interceptors/auth.NewUnary.func1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80}, 0xc0008fc040, 0xc0008fc060)
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/interceptors/auth/auth.go:127 +0x41b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80}, 0xc0010b33f8, 0x490997)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:33 +0xc8
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/cs3org/reva/v2/internal/grpc/interceptors/log.NewUnary.func1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80}, 0xc0008fc040, 0xc0008fc0a0)
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/interceptors/log/log.go:39 +0x9a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/cs3org/reva/v2/internal/grpc/interceptors/useragent.NewUnary.func1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80}, 0x1, 0xc0008fc0c0)
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/interceptors/useragent/useragent.go:38 +0xe9
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d4660}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/cs3org/reva/v2/internal/grpc/interceptors/token.NewUnary.func1({0x40b3cc0, 0xc0013d45d0}, {0x3ed6920, 0xc0000c2a80}, 0x3f9be00, 0xc0008fc0e0)
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/interceptors/token/token.go:44 +0x159
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d45d0}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/cs3org/reva/v2/internal/grpc/interceptors/appctx.NewUnary.func1({0x40b3cc0, 0xc0013d44b0}, {0x3ed6920, 0xc0000c2a80}, 0x18, 0xc0008fc100)
	github.com/cs3org/reva/v2@v2.1.0/internal/grpc/interceptors/appctx/appctx.go:42 +0x5ab
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x40b3cc0, 0xc0013d44b0}, {0x3ed6920, 0xc0000c2a80})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x40b3cc0, 0xc0013d44b0}, {0x3ed6920, 0xc0000c2a80}, 0xc0000a1bd0, 0x3b66860)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1._ProviderAPI_CreateStorageSpace_Handler({0x3fd7440, 0xc0001d2320}, {0x40b3cc0, 0xc0013d44b0}, 0xc0000c2a20, 0xc00141adb0)
	github.com/cs3org/go-cs3apis@v0.0.0-20220126114148-64c025ccdd19/cs3/storage/provider/v1beta1/provider_api.pb.go:5950 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00184e000, {0x40e3338, 0xc0007691e0}, 0xc0010f4480, 0xc000e5a7e0, 0x5a342b0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00184e000, {0x40e3338, 0xc0007691e0}, 0xc0010f4480, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294
2022-05-09T08:23:33Z ERR runtime error: invalid memory address or nil pointer dereference pkg=rgrpc service=storage traceid=00000000000000000000000000000000
2022-05-09T08:23:33Z ERR unary code=Internal end="09/May/2022:08:23:33 +0000" from=tcp://172.16.10.226:58786 pkg=rgrpc service=storage start="09/May/2022:08:23:33 +0000" time_ns=16548482 traceid=00000000000000000000000000000000 uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateStorageSpace user-agent=grpc-go/1.45.0
2022-05-09T08:23:44Z DBG refreshing external service-registration service={"endpoints":[],"metadata":null,"name":"com.owncloud.storage.metadata","nodes":[{"address":"0.0.0.0:9215","id":"com.owncloud.storage.metadata-5e906fea-03c1-4209-ae9b-63eaa0818399","metadata":{"broker":"http","protocol":"grpc","registry":"kubernetes","server":"grpc","transport":"grpc"}}],"version":"1.19.1"}
```

Error log from `accounts` pod:
```
2022-05-09T08:22:04Z ERR handler init error="could not create metadata storage: cs3 backend was configured but failed to start: rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" service=accounts
```

**Comment by NexZhu** [comment]
I found that the real cuase is NAS volume not supporting `xattr` causing error:
`Failed to set all xattrs: xattr.Set /var/lib/ocis/storage/metadata/spaces/95/cb8724-03b2-11eb-a0a6-c33ef8ef53ad/nodes/95/cb/87/24/-03b2-11eb-a0a6-c33ef8ef53ad user.ocis.blobsize: operation not supported`
